### ISSUE TITLE
"Fix writable cache" Problem

### ISSUE THREAD

**Issue by cajetanus** [khaledhosny/luaotfload#59]
There seems to be a problem in either the fontspec package or in luaotfload and I cannot find the source of the error. 

I am just trying to compile a simple lualatex document, which you can see [here](https://gist.github.com/cajetanus/e430bb9a39656ee3674d) It will compile with lualatex without problem when the \usepackage{fontspec} is commented out. However, when it is as written, we get an error. The log is [here](https://gist.github.com/cajetanus/8127162d7b282c0320d0), but the critical lines are here:

```
Lua module: luaotfload-main 2014/08/10 2.50003 OpenType layout system.
quiting: fix your writable cache path
```

It seems that luaotfload is at fault, but I can't seem to answer how. I am using the latest texlive with tlmgr updates all to the latest versions. I have searched all over google and no luck - though there are some mentions of problems with fontenc there is no solution given.

Thank you for any help or links in the right direction. I can post this issue on fontenc if you think they are at fault, but most of the google searches indicated that something changed in the last release, and luaotfload is more recent than the fontspec in CTAN.

**Comment by khaledhosny** [comment]
This repository is obsolete and kept for historical reference, please read the project description and follow the link there.
