### ISSUE TITLE
Misplaced letters

### ISSUE THREAD

**Issue by jbezos** [khaledhosny/luaotfload#60]
There are misplaced letters in the following example, because some internal kerns are inserted at the wrong places. It seems it has been fixed in ConTeXt, but unfortutately the context loader doesn't work for me. Are there plans to update luaotfload?

```
\documentclass{book}
\usepackage{fontspec}
\setmainfont[Script=Arabic]{FreeSerif}

\begin{document}
\hsize 3.5cm

\pardir TRT
\textdir TRT

1234 الإشارات برهن

\mbox{1234 الإشارات برهن}

\halign{#\cr 1234 الإشارات برهن\cr}

\end{document}
```

**Comment by khaledhosny** [comment]
This repository is unmaintained, you probably want to report this to https://github.com/lualatex/luaotfload.
